# Place this file at .streamlit/secrets.toml in your repo for Streamlit Cloud
# Streamlit will expose these as environment variables so os.getenv(...) works.
OPENAI_API_KEY = "sk-REEMPLAZAR"
GOOGLE_API_KEY = "AIza-REEMPLAZAR"
